#! /usr/bin/env python
"""NumPy_and_CuPy.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jkLN11OATK0foFGN1-pBLFqHdx0nD4nK
"""

import time
import numpy as np
# import cupy as cpnp


def get_w_np(x, t):
    xx = np.dot(x.T, x)
    xx_inv = np.linalg.inv(xx)
    xt = np.dot(x.T, t)
    w = np.dot(xx_inv, xt)
    return w


N = 10

x = np.random.rand(N, N)
t = np.random.rand(N, 1)
w = get_w_np(x, t)

print(w)


times_cpu = []

for N in [10, 100, 1000, 10000]:
    np.random.seed(0)
    x = np.random.rand(N, N)
    t = np.random.rand(N, 1)
    time_start = time.time()
    w = get_w_np(x, t)
    time_end = time.time()
    elapsed_time = time_end - time_start
    print(f'N={N:>5}:{elapsed_time:>8.5f} sec')
    times_cpu.append(elapsed_time)
