"""
Django settings for tph project.

Generated by 'django-admin startproject' using Django 3.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'ci+8#r9o9s8a_@u)v*c6m%hg*+e(i6@#z3l#2po#1m6=tz4&6t'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1', '192.168.1.16']


# Application definition

INSTALLED_APPS = [
    'monitor.apps.MonitorConfig',
    'compressor',
    'background_task',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_plotly_dash.apps.DjangoPlotlyDashConfig',
    # 'dpd_static_support',
    'rest_framework',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_plotly_dash.middleware.BaseMiddleware',
    'django_plotly_dash.middleware.ExternalRedirectionMiddleware',
]

# https://docs.djangoproject.com/en/3.0/ref/clickjacking/
X_FRAME_OPTIONS = 'SAMEORIGIN'

ROOT_URLCONF = 'tph.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [Path(BASE_DIR).joinpath('templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'tph.wsgi.application'

ASGI_APPLICATION = 'tph.routing.application'

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        # 'ENGINE': 'django.db.backends.sqlite3',
        # 'NAME': BASE_DIR / 'db.sqlite3',
        'ENGINE': 'django.db.backends.mysql',
        'OPTIONS': {
            'read_default_file': '/home/mitsu/.config/mariadb.cnf',
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'ja'

TIME_ZONE = 'Asia/Tokyo'

USE_I18N = True

USE_L10N = True

USE_TZ = True

USE_THOUSAND_SEPARATOR = True


# Plotly dash settings

PLOTLY_DASH = {
    "ws_route": "ws/channel",

    "insert_demo_migrations": True,  # Insert model instances used by the demo

    "http_poke_enabled": True, # Flag controlling availability of direct-to-messaging http endpoint

    "view_decorator": None, # Specify a function to be used to wrap each of the dpd view functions

    "cache_arguments": True, # True for cache, False for session-based argument propagation

    # "serve_locally": True, # True to serve assets locally, False to use their unadulterated urls (eg a CDN)

    # "stateless_loader": "demo.scaffold.stateless_app_loader",
    }


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_ROOT = Path(BASE_DIR).joinpath('static')
STATIC_URL = '/static/'
# STATICFILES_DIRS = [
#     ps.path.join(BASE_DIR, 'static'),
# ]
STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'compressor.finders.CompressorFinder',

    'django_plotly_dash.finders.DashAssetFinder',
    'django_plotly_dash.finders.DashComponentFinder',
    'django_plotly_dash.finders.DashAppDirectoryFinder',
]

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Plotly components containing static content that should
# be handled by the Django staticfiles infrastructure

PLOTLY_COMPONENTS = [
    'dash_core_components',
    'dash_html_components',
    # 'dash_bootstrap_components',
    'dash_renderer',
    'dpd_components',
    # 'dpd_static_support',
]


# for SASS/SCSS
# https://www.accordbox.com/blog/how-use-scss-sass-your-django-project-python-way/
# https://stackoverflow.com/questions/22515611/django-sass-compressor-django-libsass-sasscompiler-command-not-found

COMPRESS_ROOT = Path(BASE_DIR).joinpath('static')
COMPRESS_PRECOMPILERS = (
    # ('text/x-scss', 'django_libsass.SassCompiler'),
    ('text/x-scss', 'pysassc {infile} {outfile}'),
)


PAGE_SIZE = 10

# for Django Rest Framework
# https://www.django-rest-framework.org
# https://www.django-rest-framework.org/tutorial/quickstart/

REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': PAGE_SIZE,
}


# for Django Background Tasks
# https://django-background-tasks.readthedocs.io/en/latest/

# MAX_ATTEMPTS = 25
# MAX_RUN_TIME = 3600
# BACKGROUND_TASK_RUN_ASYNC = False
# BACKGROUND_TASK_ASYNC_THREADS = multiprocessing.cpu_count()
# BACKGROUND_TASK_PRIORITY_ORDERING = 'DESC'


# Logging
# https://docs.djangoproject.com/en/3.0/topics/logging/

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{asctime}] {levelname} {module}.{funcName} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'DEBUG',
            # 'filters': ['require_debug_true'],
            'class': 'logging.StreamHandler',
            'formatter': 'verbose'
        },
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': 'logs/debug.log',
            'formatter': 'verbose',
        },
        'monitor': {
            # 'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': 'logs/monitor.log',
            'formatter': 'verbose',
        },
        'process_tasks': {
            # 'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': 'logs/process_tasks.log',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'WARNING',
            'propagate': True,
        },
# https://community.plot.ly/t/prevent-post-dash-update-component-http-1-1-messages/11132
# https://github.com/plotly/dash/issues/270
        'werkzeug': {
            'handlers': ['console', 'file'],
            'level': 'ERROR',
            'propagate': True,
        },
        'monitor.store_tph': {
            'handlers': ['process_tasks'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'monitor.store_tph_bg': {
            'handlers': ['process_tasks'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'monitor': {
            'handlers': ['monitor'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}


# for RPi TPH Monitor
# https://www.indoorcorgielec.com/products/rpi-tph-monitor-rev2/

BME280CH1_ADDR = 0x76
BME280CH2_ADDR = 0x77
LCD_DISP_TPH = 'P'

# for Development on your macOS, Ubuntu or MS-Windows

ON_RASPBERRY_PI = True
USE_SMBUS2 = True


# miscs

OWNER = 'ML and AI study group.'
COPYRIGHT_YEAR = '2019-2021'
DATET_FORMAT = 'Y F d'
TIME_FORMAT = 'H:i:s'
DATETIME_FORMAT = 'r'
